[package]
name = "quickwit-datetime"
version = "0.6.0"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Datetime Util crate of quickwit"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
itertools = { workspace = true }
once_cell = { workspace = true }
ouroboros = "0.15.5"
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tantivy = { workspace = true }
time = { workspace = true }
time-fmt = "0.3.8"

[dev-dependencies]
chrono = "0.4.26"
